### ISSUE TITLE
Help wanted communicating with MULTI V IV outdoor unit

### ISSUE THREAD

**Issue by espcurious** [jourdant/esphome-lgap#12]
Hey anyone who had success with using project!

I'm dipping into this world with the target to read out and control my LG MultiV.IV airconditioning system.
I've rammed my head into a wall and need a bit of help how to progress.

I hope to get suggestions for steps to take to find out if some DIP switches need to be adjusted to enable communication on the ODU, and/or debug why no communication is flowing.

**What I have tried already**
Read all I could from this project, the issues in it, and all of the links I have spotted.

I think my setup resembles the one of @jourdant, but I have very little luck communicating with the ODU and finding documentation from LG on my unit.

**My setup**
My outdoor unit is
![modeltype](https://github.com/user-attachments/assets/01c25063-5796-4ade-ba10-d93b0510df58)
![ratingplate](https://github.com/user-attachments/assets/2ba02741-19aa-4508-8170-39504ccabf8f)

With the cover off, it looks like this:
![uncovered](https://github.com/user-attachments/assets/c512a1fc-4ddd-402a-8f82-6ef0d52b85ed)

I have the m5stack atom-lite with the RS485-base 
![docs m5stack com_en_core_ATOM_Lite](https://github.com/user-attachments/assets/856548e3-6cc5-4de7-928e-5c72c90c3f1e)
![m5stack-485-base](https://github.com/user-attachments/assets/ead709c9-87a1-41ee-b2ab-5380b1454625)

It is wired up like shown in the May 19th 2024 comment in 
https://github.com/jourdant/esphome-lgap/issues/1 

My ODU has the same connectors:
![connectors](https://github.com/user-attachments/assets/87a1abab-d7e9-4923-a9fd-dbb723e0d552)

My yaml is pasted below, and I have tried all combinations of 
- swapped A and B wires 
- swapped rx and tx pins
- esp32-board-types
- baud-rates (2400, 4800, 9600, 19200, 57600, 115200)

<details>
<summary>esphome-lgap.yaml (expand)</summary>
```
esphome:
  name: esphome-lgap
  friendly_name: esphome-lgap

esp32:
#  board: m5stack-atom
  board: m5stack-core-esp32
  framework: 
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WHCS6CnXpJbJ5ukiUBqyWtcOKhu6jIcpS8tDgjFRI0Y="

ota:
  - platform: esphome
    password: "936fa2e41698aba5805bcc889625cce1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esphome-lgap Fallback Hotspot"
    password: "WXGGA9MFPPs8"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/jourdant/esphome-lgap
      ref: main
    components: [ "lgap"]
    refresh: 0sec

uart:
  tx_pin: GPIO22
  #tx_pin: GPIO19
  rx_pin: GPIO19
  #rx_pin: GPIO22
  baud_rate: 4800
  data_bits: 8
  parity: NONE
  stop_bits: 1
  id: lgap_uart1

lgap:
  - id: lgap1
    uart_id: lgap_uart1

climate:
  - platform: lgap
    id: lgap_zone_1
    name: 'Zone 1 - Living Room'
    lgap_id: lgap1
    zone: 0
  - platform: lgap
    id: lgap_zone_2
    name: 'Zone 2 - Master Bedroom'
    lgap_id: lgap1
    zone: 1
  - platform: lgap
    id: lgap_zone_3
    name: 'Zone 3 - Kitchen'
    lgap_id: lgap1
    zone: 2
  - platform: lgap
    id: lgap_zone_4
    name: 'Zone 4 - Guest Bedroom'
    lgap_id: lgap1
    zone: 3
  - platform: lgap
    id: lgap_zone_5
    name: 'Zone 5 - KC'
    lgap_id: lgap1
    zone: 4
  - platform: lgap
    id: lgap_zone_6
    name: 'Zone 6 - CK'
    lgap_id: lgap1
    zone: 5
  - platform: lgap
    id: lgap_zone_7
    name: 'Zone 7 - Hallway'
    lgap_id: lgap1
    zone: 6
```
</details>
Any suggestions for things to try are most welcome!
