### ISSUE TITLE
How to send command?

### ISSUE THREAD

**Issue by CS012019** [jourdant/esphome-lgap#3]
Hi I have a Dual Inverter Air Conditioner - M38AKH and PI-485 extension board and I am trying to control the aircon remotely using this board. 

I have a question as I am not getting any response. How exactly do I send the request? What is the format? If you could please send an example of a valid request and how exactly you send it, that would be appreciated.

I am currently sending this request over serial [0,0,0,0,2,2,5,92] and it is not working. Any help will be greatly appreciated.

**Comment by jourdant** [comment]
That's awesome you have the PI-485! According to this diagram, the LGAP pins should be 2 (BUS A/+) and 3 (BUS B/-).
<img width="715" alt="Screenshot 2024-03-23 at 4 44 53 PM" src="https://github.com/jourdant/esphome-lgap/assets/230794/df40b0c6-0c09-48e7-95f6-1b0f3a7d7331">

Which ESP32 board are you using to interface with the PI-485 board?

[Here is the work-in-progress branch](https://github.com/jourdant/esphome-lgap/blob/feature/esphome2/esphome/components/lgap/climate/lgap_climate.cpp) I currently have where I'm writing an esphome component with LGAP implemented. If you're wanting to add it to an esphome config, you'll need to add the following lines:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/jourdant/esphome-lgap
      ref: feature/esphome2
    components: [ "lgap"]
    refresh: 0sec

uart:
  id: lgap_uart1
  tx_pin: GPIO06 #update your pin
  rx_pin: GPIO07 #update your pin
  baud_rate: 4800

  debug:
      direction: BOTH
      
lgap:
  - id: lgap1
    uart_id: lgap_uart1
    flow_control_pin: GPIO05
    zone_check_wait_time: 5000ms
    send_wait_time: 4000ms
    receive_wait_time: 4000ms

    debug: True
    debug_wait_time: 2000ms
    
climate:
   - platform: lgap
     id: lgap_zone_1
     name: 'Zone 1 - Ground Floor'
     lgap_id: lgap1
     zone: 0
```
